// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "sagara/domain/entity"

	mock "github.com/stretchr/testify/mock"

	request "sagara/internal/delivery/request"

	uuid "github.com/google/uuid"
)

// OfficeRepository is an autogenerated mock type for the OfficeRepository type
type OfficeRepository struct {
	mock.Mock
}

// CountOffice provides a mock function with given fields: ctx, options
func (_m *OfficeRepository) CountOffice(ctx context.Context, options *request.Option) (int32, error) {
	ret := _m.Called(ctx, options)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, *request.Option) int32); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *request.Option) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOfficeById provides a mock function with given fields: ctx, id
func (_m *OfficeRepository) FindOfficeById(ctx context.Context, id uuid.UUID) (*entity.Office, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Office
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Office); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Office)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOffice provides a mock function with given fields: ctx, options
func (_m *OfficeRepository) GetOffice(ctx context.Context, options *request.Option) ([]*entity.Office, error) {
	ret := _m.Called(ctx, options)

	var r0 []*entity.Office
	if rf, ok := ret.Get(0).(func(context.Context, *request.Option) []*entity.Office); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Office)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *request.Option) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOfficeRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewOfficeRepository creates a new instance of OfficeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOfficeRepository(t mockConstructorTestingTNewOfficeRepository) *OfficeRepository {
	mock := &OfficeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
