INSERT INTO offices VALUES
    (gen_random_uuid(), 'Serviced Office', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '1aa03e92-fffa-47da-8041-b421556b6718'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/office-all-access.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'Co-Working Space', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'c42624eb-cf03-4a68-b75a-7fbe803d1082'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/office-all-access.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'Virtual Office', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '6b4d33ac-10da-49bc-a825-150ed3c7de88'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/office-all-access.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'Meeting Facilities', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '478738a0-a722-49ec-95ff-0f9406fa66e5'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/office-all-access.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'AXA', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'fecd8e26-289b-4bd9-9911-623ee1708eba'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/axaoffice-1.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'AXA', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '4dcf1ac2-6b23-450b-aecd-9ac6c369e373'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/axaoffice-2.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'AXA', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '33fe4e6f-5748-4b3a-b858-455a584765f7'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/axaoffice-3.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'AXA', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '99d206e4-f233-47b8-9351-6fcd85751c89'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/offer/axaoffice-4.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'GKB', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '14d4c83c-e64b-4e0f-8eb7-f0df91b49bfe'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/GKBI - office (1).png"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'GKB', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '3c881b3b-2fef-4cc2-addf-6639bb0c3963'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/GKBI - office (2).png"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'GKB', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '513009e2-8782-4daa-b6bd-5d85c087ce91'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/GKBI - office (3).png"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'GKB', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'c346a459-2b34-4baf-bd99-14bad69f4990'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/GKBI - office (4).png"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'IDX', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '466cf4b1-a656-4268-afbf-23a9a3081ecf'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IDX - Suite-07.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'IDX', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'f5c5ace1-9f6a-426e-8294-14a263808b6a'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IDX BOARDROOM.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'IDX', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '1c598ea4-21aa-45ab-8ede-a5bd62dde631'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IDX Chamber.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'IDX', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '729e1ee1-95ed-4597-ab78-32e74c2ece62'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IDX Lobby.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'OPP', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '31b80fab-482a-4706-93b8-7ec8a2623fbf'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/CEO_OPP_Board_Room_IMG_1143.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'OPP', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '96ff7863-ea59-443a-b914-a5f58cc50351'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IF_0819.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'OPP', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'c5097200-6fab-40e2-8647-db87fa1e0bef'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IF_0879.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'OPP', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', '3e58a25c-8cb9-49b7-8769-f59c08555cc1'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/IF_0949.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'SSC', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'f71af4d0-a4c7-46f3-b0e3-acbabd4f8c47'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/SSC suite 07.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'SSC', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'e1419cba-7e15-494f-ab25-fe89dad3b501'::uuid, 11, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/SSC suite 39.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'SSC', 'Room A', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'd8df8091-336f-4dd3-b3d2-b793efd30d9b'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/SSC - Suite-07-(2).jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW()),
    (gen_random_uuid(), 'SSC', 'Room B', 'Stay inspired in a shared environment with like-minded individuals pursuing their passions, and become part of a dynamic creative community that stretches throughout Asia.
Co-Wo', 'edd559c7-e837-402d-ae21-5242a31da87b'::uuid, 12, '{"capacity": 10, "table": 5, "chair": 5, "special_offer": {"title": "Special Offer: Office All Access", "description": "Easier to Access your room for 24 hours!", "image_path": "/static/office/SSC Suite 01.jpg"}, "special_price": {"image_path": "/static/price/special-price.jpg"}}', NOW(), NOW());