INSERT INTO indonesia_provinces VALUES
    (1, 'ACEH', NOW(), NOW()),
    (2, 'SUMATERA UTARA', NOW(), NOW()),
    (3, 'SUMATERA BARAT', NOW(), NOW()),
    (4, 'RIAU', NOW(), NOW()),
    (5, 'JAMBI', NOW(), NOW()),
    (6, 'SUMATERA SELATAN', NOW(), NOW()),
    (7, 'BENGKULU', NOW(), NOW()),
    (8, 'LAMPUNG', NOW(), NOW()),
    (9, 'KEPULAUAN BANGKA BELITUNG', NOW(), NOW()),
    (10, 'KEPULAUAN RIAU', NOW(), NOW()),
    (11, 'DKI JAKARTA', NOW(), NOW()),
    (12, 'JAWA BARAT', NOW(), NOW()),
    (13, 'JAWA TENGAH', NOW(), NOW()),
    (14, 'DAERAH ISTIMEWA YOGYAKARTA', NOW(), NOW()),
    (15, 'JAWA TIMUR', NOW(), NOW()),
    (16, 'BANTEN', NOW(), NOW()),
    (17, 'BALI', NOW(), NOW()),
    (18, 'NUSA TENGGARA BARAT', NOW(), NOW()),
    (19, 'NUSA TENGGARA TIMUR', NOW(), NOW()),
    (20, 'KALIMANTAN BARAT', NOW(), NOW()),
    (21, 'KALIMANTAN TENGAH', NOW(), NOW()),
    (22, 'KALIMANTAN SELATAN', NOW(), NOW()),
    (23, 'KALIMANTAN TIMUR', NOW(), NOW()),
    (24, 'KALIMANTAN UTARA', NOW(), NOW()),
    (25, 'SULAWESI UTARA', NOW(), NOW()),
    (26, 'SULAWESI TENGAH', NOW(), NOW()),
    (27, 'SULAWESI SELATAN', NOW(), NOW()),
    (28, 'SULAWESI TENGGARA', NOW(), NOW()),
    (29, 'GORONTALO', NOW(), NOW()),
    (30, 'SULAWESI BARAT', NOW(), NOW()),
    (31, 'MALUKU', NOW(), NOW()),
    (32, 'MALUKU UTARA', NOW(), NOW()),
    (33, 'PAPUA', NOW(), NOW()),
    (34, 'PAPUA BARAT', NOW(), NOW());